- name: CentOS | Install Repo
  yum:
    state: "present"
    name:
      - "epel-release"
      - "https://centos7.iuscommunity.org/ius-release.rpm"

- name: CentOS | Update All Packages
  yum:
    name: "*"
    state: "latest"