- name: Install Repo
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "epel-release"
    - "https://centos7.iuscommunity.org/ius-release.rpm"

- name: Update All Packages
  yum:
    name: "*"
    state: "latest"