---
- name: Add the PHP Repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Add the Redis Repository
  apt_repository:
    repo: ppa:chris-lea/redis-server

- name: Install Panel Dependencies
  apt:
    update_cache: "yes"
    name: "{{ item }}"
    state: "present"
  with_items:
    - "sudo"
    - "php7.2"
    - "php7.2-cli"
    - "php7.2-gd"
    - "php7.2-mysql"
    - "php7.2-pdo"
    - "php7.2-mbstring"
    - "php7.2-tokenizer"
    - "php7.2-bcmath"
    - "php7.2-xml"
    - "php7.2-fpm"
    - "php7.2-curl"
    - "php7.2-zip"
    - "python-mysqldb"
    - "nginx"
    - "curl"
    - "tar"
    - "unzip"
    - "git"
    - "redis-server"
...