---
- name: Ubuntu | Add the PHP Repository
  apt_repository:
    repo: ppa:ondrej/php
  when: ansible_distribution|lower == 'ubuntu'

- name: Ubuntu | Add the Redis Repository
  apt_repository:
    repo: ppa:chris-lea/redis-server
  when: ansible_distribution|lower == 'ubuntu'

- name: Debian | Pre-req Packages
  apt:
    name:
      - "apt-transport-https"
    state: "present"

- name: Debian | Get the php GPG key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian | Add the PHP Repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_lsb.codename }} main
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian/Ubuntu | Install Panel Dependencies
  apt:
    update_cache: "yes"
    state: "present"
    name:
      - "sudo"
      - "php7.2"
      - "php7.2-cli"
      - "php7.2-gd"
      - "php7.2-mysql"
      - "php7.2-pdo"
      - "php7.2-mbstring"
      - "php7.2-tokenizer"
      - "php7.2-bcmath"
      - "php7.2-xml"
      - "php7.2-fpm"
      - "php7.2-curl"
      - "php7.2-zip"
      - "python-mysqldb"
      - "nginx"
      - "curl"
      - "tar"
      - "unzip"
      - "git"
      - "redis-server"
...