---
- name: CentOS | Add Firewall Rules
  firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - {port: '8080/tcp'}
    - {port: '2020/tcp'}
  when: is_firewalld is defined

- name: CentOS | Add Docker to Trusted Firewall Zone
  firewalld:
    zone: trusted
    interface: docker0
    permanent: true
    state: enabled
  when: is_firewalld is defined

- include: doinstall.yml

- include: finish.yml
...