---
- name: CentOS | php-fpm config
  template:
    src: templates/phpfpm.j2
    dest: /etc/php-fpm.d/www-pterodactyl.conf

- name: CentOS | Start the php-fpm Service
  service: name=php-fpm enabled=yes state=started

- include: doinstall.yml

- name: CentOS | Remove Default Nginx Config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: CentOS | CentOS | Add Pterodactyl Nginx Config
  template:
    src: templates/nginx.j2
    dest: "/etc/nginx/conf.d/pt_{{ domain_name }}.conf"

- name: CentOS | Chroot Pterodactyl Web Root
  file:
    path: "{{ pt_dir }}"
    owner: nginx
    group: nginx
    recurse: yes

- name: CentOS | semanage fcontext
  sefcontext:
    target: '{{ pt_dir }}/storage(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: "CentOS | restorecon -R {{ pt_dir }}"
  command: "restorecon -R {{ pt_dir }}"

- name: CentOS | Set httpd_can_network_connect for SELinux
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- include: finish.yml
...