---
- include: doinstall.yml
  static: yes

- name: Debian/Ubuntu | Remove Default Nginx Config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Debian/Ubuntu | Chroot Pterodactyl Web Root
  file:
    path: "{{ pt_dir }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Debian/Ubuntu | Add Pterodactyl Nginx Config
  template:
    src: templates/nginx.j2
    dest: "/etc/nginx/sites-available/pt_{{ domain_name }}.conf"

- name: Debian/Ubuntu | Enable Nginx Config
  file:
    src: "/etc/nginx/sites-available/pt_{{ domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/pt_{{ domain_name }}.conf"
    state: link

- name: Debian/Ubuntu | Reload Nginx
  service: name=nginx enabled=yes state=reloaded

- name: Debian/Ubuntu | Finished
  debug:
    msg:
      - "IMPORTANT DETAILS:"
      - "====================================================================="
      - "Pterodactyl Database Username/Password is pterodactyl / {{ ptdb_pass }}"
      - "MariaDB/MySQL Username/Password is root / {{ db_pass }}"
      - "Pterodactyl Panel Admin Username/Password is {{ pt_user }} / {{ pt_user_pass }}"
      - "====================================================================="
      - "Please run this command to change your email settings: php artisan p:environment:mail"
...