---
- name: Check for latest version
  uri: url="https://cdn.pterodactyl.io/releases/latest.json" return_content="yes"
  register: ptversion

- name: Create Panel Folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /var/www/pterodactyl

- name: Download Daemon Files
  get_url:
    url: "https://github.com/pterodactyl/panel/releases/download/v{{ ptversion.json.panel }}/panel.tar.gz"
    dest: /var/www/pterodactyl/panel.tar.gz

- name: Extract Daemon Files
  unarchive:
    src: /var/www/pterodactyl/panel.tar.gz
    dest: /var/www/pterodactyl
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Chmod log folder
  file:
    path: /var/www/pterodactyl/storage/
    mode: 0755
    recurse: yes

- name: Chmod cache folder
  file:
    path: /var/www/pterodactyl/bootstrap/cache
    mode: 0755
    recurse: yes

- name: Install Composer
  shell: curl -sSL https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
  args:
    chdir: /var/www/pterodactyl
    creates: /usr/local/bin/composer
    warn: false

- name: Copy .env file
  copy:
    src: /var/www/pterodactyl/.env.example
    dest: /var/www/pterodactyl/.env
    remote_src: yes

- name: Install the Panel
  command: composer install --no-dev
  args:
    chdir: /var/www/pterodactyl

- name: Generate the Panel Key
  command: php artisan key:generate --force -n
  args:
    chdir: /var/www/pterodactyl

#php artisan p:environment:setup
- name: Artisan Setup
  command: php artisan p:environment:setup --author="{{ pt_email }}" --url=https://{{ domain_name }} --timezone="{{ pt_timezone }}" --cache="{{ pt_cache }}" --session="{{ pt_session }}" --queue="{{ pt_queue }}" --redis-host="{{ pt_redis_host }}" --redis-pass="{{ pt_redis_pass }}" --redis-port="{{ pt_redis_port }}" --env=production -n
  args:
    chdir: /var/www/pterodactyl
#php artisan p:environment:database
- name: Artisan Database Setup
  command: php artisan p:environment:database --host="{{ pt_db_host }}" --port="{{ pt_db_port }}" --database=panel --username=pterodactyl --password="{{ ptdb_pass }}" -n
  args:
    chdir: /var/www/pterodactyl
#php artisan p:environment:mail
- name: Artisan Mail Setup
  command: php artisan p:environment:mail --driver="{{ pt_mail_driver }}" --email="{{ pt_email }}" --from="{{ pt_email_from }}" --encryption="{{ pt_mail_encrypt }}" -n
  args:
    chdir: /var/www/pterodactyl

- name: Migrate Database
  command: php artisan migrate --seed --force -n
  args:
    chdir: /var/www/pterodactyl

- name: Generate Admin Account Password
  set_fact:
    pt_user_pass: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

#php artisan p:user:make
- name: Add Panel User
  command: php artisan p:user:make --email={{ pt_email }} --username={{ pt_user }} --name-first={{ pt_user_fname }} --name-last={{ pt_user_lname }} --password={{ pt_user_pass }} --admin=1 -n
  args:
    chdir: /var/www/pterodactyl

- name: Chroot Pterodactyl web root
  file:
    path: /var/www/pterodactyl
    owner: www-data
    group: www-data
    recurse: yes

- name: Create cron job
  cron:
    name: "Pterodactyl Queue Scheduler"
    job: "php /var/www/pterodactyl/artisan schedule:run >> /dev/null 2>&1"

- name: Remove Default Nginx Config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add Pterodactyl Nginx Config
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/pterodactyl.conf

- name: Enable Nginx Config
  file:
    src: /etc/nginx/sites-available/pterodactyl.conf
    dest: /etc/nginx/sites-enabled/pterodactyl.conf
    state: link

- name: Reload Nginx
  service: name=nginx enabled=yes state=reloaded

- name: Create the Queue Service
  template:
    src: templates/queue.j2
    dest: /etc/systemd/system/pteroq.service

- name: Start the Queue Service
  service: name=pteroq enabled=yes state=started

- name: Finished
  debug:
    msg:
      - "IMPORTANT DETAILS:"
      - "====================================================================="
      - "Pterodactyl Database Username/Password is pterodactyl / {{ ptdb_pass }}"
      - "MariaDB/MySQL Username/Password is root / {{ db_pass }}"
      - "Pterodactyl Panel Admin Username/Password is {{ pt_user }} / {{ pt_user_pass }}"
      - "====================================================================="
      - "Please run this command to change your email settings: php artisan p:environment:mail"
...