---
- name: Reload Nginx
  service: name=nginx enabled=yes state=reloaded

- name: Finished
  debug:
    msg:
      - "IMPORTANT DETAILS:"
      - "====================================================================="
      - "Pterodactyl Database Username/Password is pterodactyl / {{ ptdb_pass }}"
      - "MariaDB/MySQL Username/Password is root / {{ db_pass }}"
      - "Pterodactyl Panel Admin Username/Password is {{ pt_user }} / {{ pt_user_pass }}"
      - "====================================================================="
      - "Please run this command to change your email settings: php artisan p:environment:mail"
...