---
- name: Debian/Ubuntu | Chroot Pterodactyl Web Root
  file:
    path: "{{ pt_dir }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Debian/Ubuntu | Start the Panel
  command: "php artisan up"
  args:
    chdir: "{{ pt_dir }}"
    
- name: Debian/Ubuntu | Start the Queues
  command: "php artisan queue:restart"
  args:
    chdir: "{{ pt_dir }}"
...