---
- name: Debian/Ubuntu | Add the NodeJS Repository
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  args:
    warn: False

- name: Debian/Ubuntu | Install Daemon Dependencies
  apt:
    update_cache: "yes"
    name: "{{ item }}"
    state: "present"
  with_items:
    - "sudo"
    - "tar"
    - "unzip"
    - "make"
    - "gcc"
    - "g++"
    - "python"
    - "curl"
    - "nodejs"
...