---
- name: Get service List
  service_facts:

- name: Check for firewalld
  set_fact:
    is_firewalld: true
  when: ansible_facts.services.firewalld is defined

# Required for Let's Encrypt, and Panel
- name: Add Firewall Rules
  firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - {port: '443/tcp'}
    - {port: '80/tcp'}
  when: is_firewalld is defined
...