---
- name: Debian/Ubuntu | Remove Old Docker versions
  apt:
    name: "{{ item }}"
    state: "absent"
  with_items:
    - "docker"
    - "docker-engine"
    - "docker.io"

- name: Debian/Ubuntu | Install Docker Dependencies
  apt:
    update_cache: "yes"
    name: "{{ item }}"
    state: "present"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "curl"

- name: Debian | Debian Specific Dependencies
  apt:
    update_cache: "yes"
    name: "gnupg2"
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian/Ubuntu | Get the Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: "present"

- name: Debian/Ubuntu | Add the Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable
    state: "present"

- name: Debian/Ubuntu | Install DockerCE
  apt: 
    update_cache: "yes"
    name: "docker-ce"
    state: "present"
    
- name: Debian/Ubuntu | Start the Docker Service
  service: name=docker state=started enabled=yes
...